const data = {
  products: [
    {
      id: 1,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "../products/image 20.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 2,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 21.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 3,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 22.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 4,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 23.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 5,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 23.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 6,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 23.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
  ],
  recommendedProducts: [
    {
      id: 1,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 20.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 2,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 20.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 3,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 20.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 4,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 20.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
  ],
  trendingProducts: [
    {
      id: 1,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 20.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 2,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 21.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 3,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 22.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 4,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 23.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 5,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/image 22.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
  ],
  featuredProducts: [
    {
      id: 1,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/featured/image 13.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 2,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/featured/image 14.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 3,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/featured/image 15.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 4,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/featured/image 16.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
    {
      id: 5,
      productName: "Nice and lovely",
      href: "#",
      imgSrc: "./products/featured/image 14.png",
      imageAlt: "Nice and Lovely",
      price: 2000,
      description: "Body Lotion",
      rating: 5.5,
      sold: 300,
    },
  ],
  testimonials: [
    {
      id: 1,
      imageSrc: "./testimonials/testimony 1.png",
      message: "The Best service you can get around the city",
    },
    {
      id: 2,
      imageSrc: "./testimonials/testimony 2.png",
      message: "The Best service you can get around the city",
    },
    {
      id: 3,
      imageSrc: "./testimonials/testimony 3.png",
      message: "The Best service you can get around the city",
    },
    {
      id: 4,
      imageSrc: "./testimonials/testimony 4.png",
      message: "The Best service you can get around the city",
    },
  ],
};
export default data;
